# Generated by Django 4.0.4 on 2022-05-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercenter',
            name='membersince',
        ),
        migrations.AlterField(
            model_name='membercenter',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='membercenter',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
