# Generated by Django 4.0.4 on 2022-05-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_remove_membercenter_membersince_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='locationid',
            new_name='location_id',
        ),
    ]
