# Generated by Django 4.0.4 on 2022-06-01 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0004_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
