# Generated by Django 4.0.4 on 2022-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_businessowner',
            field=models.BooleanField(default=False, verbose_name='business ownerstatus'),
        ),
    ]
